id: P004588
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG12972
  title: གཉགས་ལུགས་ཕུར་པའི་འདོན་ཆ།
  author: ''
  volumes:
    a41b7141b23f4a3abe29a82680a18406:
      image_group_id: I1KG13030
      title: ''
      volume_number: 1
      total_pages: 236
