id: P004588
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 11:43:05.305488
source_metadata:
  id: bdr:W1KG12972
  title: གཉགས་ལུགས་ཕུར་པའི་འདོན་ཆ།
  author: ''
  volumes:
    a41b7141b23f4a3abe29a82680a18406:
      image_group_id: I1KG13030
      title: ''
      volume_number: 1
      total_pages: 236
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
