id: I1C5CC559
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T13:51:49+00:00'
last_modified: '2022-06-08T02:08:26.618020+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12972
  title: གཉགས་ལུགས་ཕུར་པའི་འདོན་ཆ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E07E:
      image_group_id: I1KG13030
      title: ''
      total_pages: 236
      order: 1
      base_file: E07E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
